# Numpy execises


In [ ]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9


In [3]:
# Expected output
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(0,10,1) #np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3×3 numpy array of all True’s

In [5]:
np.full((3,3),True)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Extract all odd numbers from arr


In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Expected output
#> array([1, 3, 5, 7, 9])

arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

4. Replace all odd numbers in arr with -1


In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Expected output
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

5. Replace all odd numbers in arr with -1 in a new output without changing arr


In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Expected output
#>  arr array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#>  output array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

new_arr = np.where(arr % 2 != 0, -1)
new_arr

ValueError: either both or neither of x and y should be given

6. Convert a 1D array to a 2D array with 2 rows


In [9]:
arr = np.arange(10)
# Expected output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

arr.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

7. Stack arrays a and b vertically


In [11]:
a = np.arange(10).reshape(2,5)
b = np.ones([2,5])

In [12]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Expected output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

np.vstack([a,b.astype(int)]) #np.concatenate([a,b.astype(int)], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

8. Stack the arrays a and b horizontally.

In [ ]:
a = np.arange(10).reshape(2,5)
b = np.ones([2,5])

In [19]:
# Expected output
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.hstack([a,b.astype(int)]) #np.concatenate([a,b.astype(int)], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

9. Get the positions where elements of a and b match

In [69]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Expected output
#> (array([1, 3, 5, 7]),)
np.where(a == b)

(array([1, 3, 5, 7]),)

10. Get all items between 5 and 10 from a.

In [26]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
# Expected output
#>(array([6, 9, 10]),)

a[np.where((a > 4) & (a < 11))]

array([ 6,  9, 10])

11. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = iris[:,0].astype(float)
np.mean(sepallength)
np.median(sepallength)
np.std(sepallength)

0.8253012917851409

12. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = sepallength / np.linalg.norm(sepallength)
sepallength

array([0.07056264, 0.06779548, 0.06502832, 0.06364474, 0.06917906,
       0.07471338, 0.06364474, 0.06917906, 0.06087757, 0.06779548,
       0.07471338, 0.0664119 , 0.0664119 , 0.05949399, 0.08024771,
       0.07886413, 0.07471338, 0.07056264, 0.07886413, 0.07056264,
       0.07471338, 0.07056264, 0.06364474, 0.07056264, 0.0664119 ,
       0.06917906, 0.06917906, 0.07194622, 0.07194622, 0.06502832,
       0.0664119 , 0.07471338, 0.07194622, 0.07609697, 0.06779548,
       0.06917906, 0.07609697, 0.06779548, 0.06087757, 0.07056264,
       0.06917906, 0.06226115, 0.06087757, 0.06917906, 0.07056264,
       0.0664119 , 0.07056264, 0.06364474, 0.0733298 , 0.06917906,
       0.09685068, 0.0885492 , 0.0954671 , 0.07609697, 0.08993278,
       0.07886413, 0.08716562, 0.06779548, 0.09131636, 0.07194622,
       0.06917906, 0.08163129, 0.08301487, 0.08439845, 0.07748055,
       0.09269994, 0.07748055, 0.08024771, 0.08578203, 0.07748055,
       0.08163129, 0.08439845, 0.08716562, 0.08439845, 0.08854

13. Find the number and position of missing values in iris_2d's sepallength (1st column)

In [40]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20), ] = np.nan
sepallength = iris_2d[:,0]
print("number:" + str(np.sum(np.isnan(sepallength))))
print("position" + str(np.where(np.isnan(sepallength))))

number:6
position(array([ 46,  52,  56,  97, 121, 146]),)


14. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [42]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
sepallength = iris_2d[:,0]
petallength = iris_2d[:,2]
iris_2d[(petallength > 1.5) & (sepallength < 5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

15. Find out if iris_2d has any missing values.

In [43]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

16. Replace all occurrences of nan with 0 in numpy array

In [44]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)] = 0
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 0. , 0.2],
       [5. , 0. , 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [0. , 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 0. , 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 0. , 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

17. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [88]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3,4])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')#only to identify the columns

sepallength = iris_2d[:,0]
petallength = iris_2d[:,2]
volume = (np.pi * petallength * sepallength**2) / 3
volume = volume[:,np.newaxis]
np.hstack([iris_2d,volume])


array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
                   nan, 3.81326516e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
                   nan, 3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
                   nan, 3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
                   nan, 3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
                   nan, 3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
                   nan, 5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
                   nan, 3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
                   nan, 3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
                   nan, 

18. Find the most frequent value of petal length (3rd column) in iris dataset.

In [83]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petallength = iris[:,2]
vals, count = np.unique(petallength,return_counts=True)

vals[np.argmax(count)]

b'1.5'

19. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [86]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a > 30] = 30
a[a < 10] = 10
a

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

20.  Drop all nan values from a 1D numpy array

In [64]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
#Expected output
# array([ 1.,  2.,  3.,  5.,  6.,  7.])
arr[~np.isnan(arr)].astype(float)

array([1., 2., 3., 5., 6., 7.])