# Pipelines

* Pipelines sequentially apply **a list of transforms** and a **final estimator**.

    * Intermediate steps of the pipeline must be ‘transforms’, that is, they must implement fit and transform methods.
    * The final estimator only needs to implement fit.

* The purpose of the pipeline is to assemble several steps that can be cross-validated together while setting different parameters.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

## Simple Pipeline

The simple pipeline is composed of the folloing steps:
- Transformation
    - Scaling values between 0 and 1
    - PCA (we keep 2 components)
- Estimator
    - Logistic Regression

### Transformation


In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer

preprocessing_transformer = Pipeline(steps=[('normalize', Normalizer()),
                                             ('scale_01', MinMaxScaler(feature_range=(0, 1))),
                                             ('PCA', PCA(n_components=2))])
# preprocessing_transformer = Pipeline(steps=[('scale_01', MinMaxScaler(feature_range=(0, 1))),
#                                             ('PioggiaPCA', PCA(n_components=2))])

### Estimator

In [5]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', multi_class='auto')

### Creating and evaluating the Pipeline

In [6]:
from sklearn.metrics import accuracy_score

# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[('preprocessing_transformer', preprocessing_transformer),
                               ('model', model)
                              ], verbose = True)

# my_pipeline = Pipeline(steps=[('scale_01', MinMaxScaler(feature_range=(0, 1))),
#                              ('PioggiaPCA', PCA(n_components=2)),
#                              ('model', model)
#                             ], verbose = True)

# Preprocessing of training data, fit model
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_valid)

# Evaluate the model
score = accuracy_score(y_valid, preds)
print('Accuracy Score:', score)

[Pipeline]  (step 1 of 2) Processing preprocessing_transformer, total=   0.0s
[Pipeline] ............. (step 2 of 2) Processing model, total=   0.0s
Accuracy Score: 0.9666666666666667


/usr/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


### Analyzing the transformation

In [7]:
X_train

array([[6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.7, 3.8, 1.7, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.5, 1.6, 0.6],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2

In [8]:
transformed_Dataset = preprocessing_transformer.fit_transform(X_train)

In [9]:
#preprocessing_transformer.transform(X_valid)

In [10]:
transformed_Dataset

array([[ 0.48187891, -0.08794552],
       [ 0.39447387, -0.19185301],
       [-0.82742985, -0.00776855],
       [ 0.43554794, -0.08147243],
       [ 0.63857614, -0.08186638],
       [ 0.30759918, -0.07433297],
       [-0.78595435, -0.00622101],
       [ 0.47310646, -0.00917393],
       [ 0.2417868 , -0.01815521],
       [ 0.17135009,  0.15847256],
       [ 0.5044493 , -0.01085657],
       [-0.83748787, -0.02827408],
       [ 0.4603074 , -0.00978699],
       [-0.63653012, -0.14596354],
       [-0.84699402, -0.03374869],
       [ 0.20913949,  0.2511393 ],
       [ 0.47705843, -0.03663131],
       [ 0.6178794 , -0.1890083 ],
       [ 0.49168655,  0.16197931],
       [ 0.55533544,  0.10811145],
       [ 0.16253613,  0.16840577],
       [ 0.50934561,  0.10026196],
       [ 0.27280092, -0.06517446],
       [ 0.16924271,  0.1877243 ],
       [ 0.43835032,  0.05529122],
       [ 0.38120198,  0.05533612],
       [ 0.63234123, -0.22810484],
       [ 0.51014492,  0.08361224],
       [ 0.12789826,

In [11]:
type(transformed_Dataset)

numpy.ndarray

In [12]:
tra_df = pd.DataFrame(transformed_Dataset)

In [13]:
tra_df.shape

(120, 2)

In [14]:
tra_df.head()

0         1
0  0.481879 -0.087946
1  0.394474 -0.191853
2 -0.827430 -0.007769
3  0.435548 -0.081472
4  0.638576 -0.081866

In [17]:
# Simple check
normal = Normalizer()
scaled = MinMaxScaler(feature_range=(0, 1))

normalized_X_train =normal.fit_transform(X_train)
scaled_X_train = scaled.fit_transform(normalized_X_train)

print(scaled_X_train[:4])

pcaed = PCA(n_components=2)
pca_X_train = pcaed.fit_transform(scaled_X_train)


[[0.14611345 0.27292178 0.92949961 0.74911544]
 [0.1214028  0.40173613 0.88194002 0.73371565]
 [0.71420707 0.83303704 0.13937648 0.06719597]
 [0.2177421  0.30550362 0.86886994 0.80557741]]


array([[ 0.48187891, -0.08794552],
       [ 0.39447387, -0.19185301],
       [-0.82742985, -0.00776855],
       [ 0.43554794, -0.08147243],
       [ 0.63857614, -0.08186638],
       [ 0.30759918, -0.07433297],
       [-0.78595435, -0.00622101],
       [ 0.47310646, -0.00917393],
       [ 0.2417868 , -0.01815521],
       [ 0.17135009,  0.15847256],
       [ 0.5044493 , -0.01085657],
       [-0.83748787, -0.02827408],
       [ 0.4603074 , -0.00978699],
       [-0.63653012, -0.14596354],
       [-0.84699402, -0.03374869],
       [ 0.20913949,  0.2511393 ],
       [ 0.47705843, -0.03663131],
       [ 0.6178794 , -0.1890083 ],
       [ 0.49168655,  0.16197931],
       [ 0.55533544,  0.10811145],
       [ 0.16253613,  0.16840577],
       [ 0.50934561,  0.10026196],
       [ 0.27280092, -0.06517446],
       [ 0.16924271,  0.1877243 ],
       [ 0.43835032,  0.05529122],
       [ 0.38120198,  0.05533612],
       [ 0.63234123, -0.22810484],
       [ 0.51014492,  0.08361224],
       [ 0.12789826,

## ColumnTransformer: Managing different kinds of transformers on different columns:
Extracted and extended from a kaggle.com tutorial

Applies transformers to columns of an array or pandas DataFrame.

This estimator allows different columns or column subsets of the input to be transformed separately and the features generated by each transformer will be concatenated to form a single feature space. This is useful for heterogeneous or columnar data, to combine several feature extraction mechanisms or transformations into a single transformer.

In [16]:
dataset = pd.read_csv("melb_data.csv")
dataset.head(5)

FileNotFoundError: [Errno 2] No such file or directory: 'melb_data.csv'

In [ ]:
dataset.dtypes

In [ ]:
dataset.shape

In [ ]:
dataset.describe()

In [ ]:
dataset['Price']

In [ ]:
#dataset = dataset[dataset['Price'].isnull()==False]

In [ ]:
columns = dataset.columns.to_list()
columns

In [ ]:
if 'Price' in columns:
  columns.remove('Price')

X = dataset[columns]
y = dataset['Price']

In [ ]:
X.info()

In [ ]:
#X = X[['Longtitude', 'Lattitude', 'YearBuilt', 'Car', 'Bathroom', 'Bedroom2', 'Rooms', 'Postcode']]
#X.isnull().any(axis=0)
#X.fillna(0, inplace=True)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

We construct the full pipeline in three steps.
* Step 1: Define Preprocessing Steps
* Step 2: Define the Model
* Step 3: Create and Evaluate the Pipeline

### Step 1: Define Preprocessing Steps

Similar to how a pipeline bundles together preprocessing and modeling steps, we use the ColumnTransformer class to bundle together different preprocessing steps. The code below:
- imputes missing values in numerical data, and
- imputes missing values and applies a one-hot encoding to categorical data.

In [ ]:
# "Cardinality" means the number of unique values in a column
# Select categorical columns with relatively low cardinality (convenient but arbitrary)
categorical_cols = [cname for cname in X_train.columns if
                    X_train[cname].nunique() < 10 and
                    X_train[cname].dtype == "object"]

# Select numerical columns
numerical_cols = [cname for cname in X_train.columns if
                X_train[cname].dtype in ['int64', 'float64']]

In [ ]:
categorical_cols

In [ ]:
numerical_cols

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='most_frequent')

# Preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse = False))
])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[
       ('num', numerical_transformer, numerical_cols),
       ('cat', categorical_transformer, categorical_cols)
    ])

### Step 2: Define the Model

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=10, random_state=0)

### Step 3: Create and Evaluate the Pipeline

In [ ]:
from sklearn.metrics import mean_absolute_error

# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[
                              ('preprocessor', preprocessor),
                              ('model', model),
                             ])

# Preprocessing of training data, fit model
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_test)

# Evaluate the model
score = mean_absolute_error(y_test, preds)
print('MAE:', score)

In [ ]:
sum(preds==np.NAN)

In [ ]:
sum(y_test==np.NAN)

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, preds)

In [ ]:
pd.DataFrame({'label':y_test, 'preds':preds}).head(4)

### Parameter tuning

Setting parameters of the various steps is enabled by using their names and the parameter name separated by a ‘__’

In [ ]:
# Example using a Grid Search
from sklearn.model_selection import GridSearchCV

parameters = {
    'model__n_estimators': [1,5,10],
    'preprocessor__num__strategy': ['most_frequent','constant'],
    'preprocessor__cat__imputer__strategy': ['most_frequent','constant'],
}

gs_clf = GridSearchCV(my_pipeline, parameters, scoring='neg_mean_absolute_error', cv=5, n_jobs=-1)

gs_clf.fit(X, y)

In [ ]:
gs_clf.best_params_

In [ ]:
gs_clf.best_score_

Applying the pipeline to some attributes only

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='most_frequent')

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
        transformers=[('num', numerical_transformer, numerical_cols)],
        remainder='passthrough')

In [ ]:
numerical_cols

In [ ]:
#This generates an error!

from sklearn.metrics import mean_absolute_error

# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[
                              ('preprocessor', preprocessor),
                              ('model', model),
                             ])

# Preprocessing of training data, fit model
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_test)

# Evaluate the model
score = mean_absolute_error(y_test, preds)
print('MAE:', score)

Remainder with estimator

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='most_frequent')


# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
        transformers=[('num', numerical_transformer, numerical_cols)],
        remainder=OneHotEncoder(handle_unknown='ignore', sparse = False))

In [ ]:
from sklearn.metrics import mean_absolute_error

# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[
                              ('preprocessor', preprocessor),
                              ('model', model),
                             ])

# Preprocessing of training data, fit model
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_test)

# Evaluate the model
score = mean_absolute_error(y_test, preds)
print('MAE:', score)

Alternative techniques to indicate columns

In [ ]:
numerical_cols

In [ ]:
X_train.columns.get_indexer(numerical_cols)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='most_frequent')


# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[('num', numerical_transformer, X_train.columns.get_indexer(numerical_cols))])

In [ ]:
preprocessor.fit_transform(X_train)

Be carefull!

In [ ]:
numerical_cols

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer


# Preprocessing for all dataset
simple=SimpleImputer(strategy='most_frequent')

# Preprocessing for numerical data
numerical_transformer = Normalizer()


# Bundle preprocessing for numerical
preprocessor = ColumnTransformer(
    transformers=[('num', numerical_transformer, numerical_cols)])

# Bundle preprocessing
preprocessing_transformer = Pipeline(steps=[('simple', simple),
                                            ('preprocessor', preprocessor)
                                            ])

In [ ]:
preprocessing_transformer.fit_transform(X_train)

In [ ]:
X_train.columns.get_indexer(numerical_cols)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer


# Preprocessing for all dataset
simple=SimpleImputer(strategy='most_frequent')

# Preprocessing for numerical data
numerical_transformer = Normalizer()


# Bundle preprocessing for numerical
preprocessor = ColumnTransformer(
    transformers=[('num', numerical_transformer, X_train.columns.get_indexer(numerical_cols))])

# Bundle preprocessing
preprocessing_transformer = Pipeline(steps=[('simple', simple),
                                            ('preprocessor', preprocessor)
                                            ])

In [ ]:
preprocessing_transformer.fit_transform(X_train)

## FeatureUnion: Applying multiple transformers in parallel

Concatenates results of multiple transformer objects.

This estimator applies a list of transformer objects in parallel to the input data, then concatenates the results. This is useful to combine several feature extraction mechanisms into a single transformer.

In [ ]:
from sklearn.pipeline import FeatureUnion
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

In [ ]:
X.shape

In [ ]:
iris.feature_names

In [ ]:
# This dataset is way too high-dimensional. Better do PCA:
pca = PCA(n_components=2)

# Maybe some original features where good, too?
selection = SelectKBest(k=2)

#Normalizing is always a good choice
scaler = MinMaxScaler(feature_range=(0, 1))

# Build estimator from PCA and Univariate selection:
combined_features = FeatureUnion([("pca", pca), ("univ_select", selection), ("normal", scaler)])

In [ ]:
X.shape

In [ ]:
pca.fit_transform(X).shape[1]

In [ ]:
selection.fit_transform(X, y).shape[1]

In [ ]:
scaler.fit_transform(X).shape[1]

In [ ]:
# Use combined features to transform dataset:
X_features = combined_features.fit(X, y).transform(X)
print("Combined space has", X_features.shape[1], "features")

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()


# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[('combined_features', combined_features),
                              ('model', model)
                             ], verbose = True)

# Preprocessing of training data, fit model
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_valid)

# Evaluate the model
score = accuracy_score(y_valid, preds)
print('Accuracy Score:', score)

## FunctionTransformer: Constructs a transformer from an arbitrary callable.

Concatenates results of multiple transformer objects.

A FunctionTransformer forwards its X (and optionally y) arguments to a user-defined function or function object and returns the result of this function.

In [ ]:
from sklearn.preprocessing import FunctionTransformer
from sklearn.ensemble import RandomForestRegressor

dataset = pd.read_csv("melb_data.csv")
columns = dataset.columns.to_list()
columns.remove('Price')

X = dataset[columns]
y = dataset['Price']

X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

#Selecting the numerical columns
def columns_num(X):
    numerical_cols = [cname for cname in X.columns if  X[cname].dtype in ['int64', 'float64']]
    return X.loc[:,numerical_cols]

fill_na_transformer = Pipeline(steps=[ ('drop_cols', FunctionTransformer(columns_num, validate=False)),
                                       ('fill_na', SimpleImputer(strategy='most_frequent'))  ], verbose=True)


model = RandomForestRegressor(n_estimators=100, random_state=0)



# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[('preprocessor', fill_na_transformer),
                              ('model', model)
                             ])

# Preprocessing of training data, fit model
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_valid)

# Evaluate the model
#score = mean_absolute_error(y_valid, preds)
#print('MAE:', score)

In [ ]:
fill_na_transformer.fit_transform(X)

In [ ]:
fill_na_transformer = Pipeline(steps=[ ('drop_cols', FunctionTransformer(columns_num, validate=True)),
                                       ('fill_na', SimpleImputer(strategy='most_frequent'))  ])

In [ ]:
fill_na_transformer.fit_transform(X)

In [ ]:
columns_num(X)