# Numpy

- NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.
- NumPy arrays are like Python’s built-in list type,
    - they provide much more efficient storage and data operations as the arrays grow larger in size.
- NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python


In [4]:
import numpy as np

# The NumPy ndarray: A Multidimensional Array Object
- N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets
- Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax
- An ndarray is a generic multidimensional container for homogeneous data
  - all of the elements must be the **same type**,
  - **shape**, a tuple indicating the size of each dimension,
  - **dtype**, an object describing the data type of the array.

## Creating ndarrays
- the ***array*** function accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data


In [2]:
data1 = [1, 3, 5, 7, 9, 11]
data1

[1, 3, 5, 7, 9, 11]

In [3]:
type(data1)

list

In [5]:
arr1 = np.array(data1)
arr1

array([ 1,  3,  5,  7,  9, 11])

In [7]:
arr1.ndim

(6,)

In [8]:
data2 = [1, 3.7, 5, 7, 9, 11.4] 
data2

[1, 3.7, 5, 7, 9, 11.4]

In [10]:
arr2 = np.array(data2) #all float because data are homogeneous
arr2

array([ 1. ,  3.7,  5. ,  7. ,  9. , 11.4])

In [ ]:
for x in arr2:
  print(x)

## Element-Wise Operations

In [11]:
arr2 * 100

array([ 100.,  370.,  500.,  700.,  900., 1140.])

In [ ]:
arr2 + arr1   # arr1 and arr2 have the same shape

In [6]:
arr1.shape

(6,)

In [ ]:
arr2.shape

In [7]:
arr3 = np.array([1, 2])

In [8]:
arr1

array([ 1,  3,  5,  7,  9, 11])

In [15]:
arr1 + arr3 #doesn't work because operands could not be broadcast together with shapes

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [10]:
data_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #list of list

In [ ]:
type(data_2)

In [ ]:
data_2[1][0]

In [18]:
data_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
arr_2 = np.array(data_2) 
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr_2.ndim

2

In [13]:
arr_2.shape

(3, 3)

In [ ]:
arr_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3

In [ ]:
arr_3.shape

In [ ]:
arr_3.ndim

- Other techniques for initializing ndarrays
  - ones: arrays fill with value 1.0 (default = float)
  - zeros: arrays fill with all 0.0
  - empty : arrays fill with random value 
  - eye: identity matrix

In [ ]:
np.ones(16)

In [14]:
np.ones((16,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.empty((3, 4))

array([[4.85991684e-310, 0.00000000e+000, 6.14573021e-310,
        6.14572429e-310],
       [6.14572429e-310, 6.14572429e-310, 6.14572429e-310,
        6.14572429e-310],
       [6.14572429e-310, 6.14572429e-310, 6.14573021e-310,
        6.14572429e-310]])

In [15]:
np.empty((3, 2, 3, 5, 6, 7, 8))

array([[[[[[[ 6.14572991e-310,  6.14572991e-310,  0.00000000e+000,
             ...,  3.28059589e-320,  0.00000000e+000,
              6.14573020e-310],
            [ 1.58891512e-320,  4.85916233e-310,  4.85916237e-310,
             ...,  0.00000000e+000,  2.12199580e-314,
              4.24399158e-313],
            [ 4.94065646e-324,  4.81693045e-310,  6.14572429e-310,
             ...,  6.14572428e-310,  6.14572428e-310,
              4.85916236e-310],
            ...,
            [ 5.83557665e-302,  5.83671590e-302,  5.83785516e-302,
             ...,  1.97109091e-268,  2.77969185e-263,
              1.19386856e-253],
            [ 5.30898812e-244,  3.82368604e-297,  1.40363759e-309,
             ...,  2.78085484e-263,  8.12441499e-206,
              3.49045482e-196],
            [ 1.49958782e-186,  2.78124250e-263,  5.83290254e-302,
             ...,  7.79446281e-153,  3.34869734e-143,
              5.83290268e-302]],

           [[ 1.43868442e-133,  2.02264183e-128,  1.02353476e-3

In [ ]:
np.ones((2, 2))

In [ ]:
np.zeros((4, 4, 4))

In [17]:
np.eye(44)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

- When constructing an array, you can specify the data type using a string

In [ ]:
np.ones(10, dtype='float32')  # Default is numpy.float64

## Basic array manipulations
- Attributes of arrays
    - Determining the size, shape, memory consumption, and data types of arrays


In [19]:
# random.randint(low, high=None, size=None, dtype=int)

a1 = np.random.randint(10, size=10)  #one-dimensional array
a2 = np.random.randint(10, size=(10, 4)) # two-dimensional array
a3 = np.random.randint(10, size=(10, 3, 3)) # three-dimensional array

In [4]:
a1

array([9, 3, 9, 1, 9, 8, 7, 8, 8, 2])

In [ ]:
a1.ndim

In [ ]:
a1.shape

In [ ]:
a2.shape

In [ ]:
a3.dtype

In [20]:
a3.itemsize # the size (in bytes) of each array element

8

In [21]:
a3.nbytes # the total size (in bytes) of the array

720

#### Indexing and slicing arrays
- Getting and setting the value of individual array elements
- Getting and setting smaller subarrays within a larger array

In [22]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

arr = np.arange(0,10,1)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5]

5

In [25]:
arr[:] # start:end(excluded); with empty index slicing return all the value 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:5]

In [27]:
arr[2:5] =111 #data is not copied, and any modifications to the view will be reflected in the source array

In [28]:
arr

array([  0,   1, 111, 111, 111,   5,   6,   7,   8,   9])

In [ ]:
lista= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
lista

In [ ]:
lista[2:5]

In [ ]:
lista[2:5]=111 #doesn't work on list

In [ ]:
lista[2:5]=[111,111,111] #we have to use an iterable
lista

In [24]:
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [25]:
array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2D[2]

In [26]:
array2D[1,1] # equal to array2D[1][1]

5

In [ ]:
array2D[1,0]

In [ ]:
array2D[1][0] = 44

In [ ]:
array2D

In [27]:
array2D[:, 0:1]

array([[1],
       [4],
       [7]])

In [28]:
array2D[2:,1:]

array([[8, 9]])

In [29]:
array2D[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

#### Boolean indexing

In [30]:
data = np.random.randn(7,5)
data

array([[ 0.30485381,  1.92882053, -0.13389702, -1.1326151 ,  1.3698955 ],
       [-0.97696532,  1.19845605,  0.4908121 , -0.49170257, -0.93593221],
       [ 0.52421499,  0.72943065,  0.44552622,  0.3064798 ,  0.11780653],
       [ 0.11083727, -0.03772574, -0.81474536, -0.38650874, -0.2791803 ],
       [ 0.94637563, -2.13565018, -1.01012274,  0.40453152, -1.05575667],
       [ 0.60517443, -0.71358661, -0.22686725, -0.50541902, -0.52033164],
       [-0.43523224,  0.17569007,  0.22984162,  0.25879102,  0.52314503]])

In [30]:
data < 0 #create new numpy array with the results of condition

array([[False, False,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False,  True, False,  True,  True],
       [False, False,  True, False, False]])

In [ ]:
data[data <0]=0 #assign value based on some condition
data

In [34]:
array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array2D == 5

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [37]:
array2D[array2D == 5]=0
array2D

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [ ]:
data

In [ ]:
data.shape


In [39]:
days = np.array(['Mon', "Tue", "Sat", "Sat", "Thu", "Fri", "Sat"]) #numpy array with string 

In [43]:
days

array(['Mon', 'Tue', 'Sat', 'Sat', 'Thu', 'Fri', 'Sat'], dtype='<U3')

In [40]:
days == "Sat"

array([False, False,  True,  True, False, False,  True])

In [ ]:
len(days)

In [41]:
data[days == "Sat"] #select the row of data based on condition on other arrays (only if two arrays have one dimension in common)

array([[ 1.98244725e+00,  4.77788224e-01,  1.21067958e-01,
         1.43314464e+00,  3.43596848e-01],
       [ 1.60310196e-03, -6.86594093e-01, -1.36070854e+00,
         6.70309602e-01, -6.04540988e-01],
       [ 1.43222485e+00,  3.83952100e-01, -4.53091766e-01,
         1.17581110e+00,  1.17858425e+00]])

In [42]:
data[days == "Mon"]

array([[ 0.38555298,  0.56529146, -0.07810912,  3.0041637 , -0.05241816]])

In [ ]:
data[days != "Mon"]

In [ ]:
data[~(days == "Mon")] # tilde mean different

In [44]:
data[(days=="Mon") | (days=="Sat")]

array([[ 3.85552977e-01,  5.65291461e-01, -7.81091189e-02,
         3.00416370e+00, -5.24181623e-02],
       [ 1.98244725e+00,  4.77788224e-01,  1.21067958e-01,
         1.43314464e+00,  3.43596848e-01],
       [ 1.60310196e-03, -6.86594093e-01, -1.36070854e+00,
         6.70309602e-01, -6.04540988e-01],
       [ 1.43222485e+00,  3.83952100e-01, -4.53091766e-01,
         1.17581110e+00,  1.17858425e+00]])

In [ ]:
data[data<=1]

In [ ]:
data

#### Fancy Indexing
- Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
- To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order

In [37]:
arr = np.empty((10, 6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9.]])

In [32]:
for i in range(10):
    arr[i] = i

In [33]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9.]])

In [34]:
arr[[2,1,4]]

array([[2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4.]])

In [35]:
arr[np.array([1,5,4,3,6,6,7])]

array([[1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.]])

#### Reshaping of arrays
- Changing the shape of a given array


In [48]:
arr.shape

(10, 6)

In [49]:
arr

array([[5.30306612e-310, 0.00000000e+000, 6.37576917e-310,
        6.37576906e-310, 6.37576907e-310, 6.37576906e-310],
       [6.37576906e-310, 2.13930425e-321, 6.37576948e-310,
        6.37576948e-310, 6.37576906e-310, 6.37576902e-310],
       [6.37576906e-310, 6.37576905e-310, 6.37576896e-310,
        6.37576905e-310, 6.37576906e-310, 6.37576906e-310],
       [6.37576971e-310, 6.37576904e-310, 6.37576906e-310,
        6.37576904e-310, 6.37576973e-310, 6.37576896e-310],
       [6.37576897e-310, 6.37576896e-310, 6.37576897e-310,
        6.37576896e-310, 6.37576897e-310, 6.37576897e-310],
       [6.37576897e-310, 6.37576896e-310, 6.37576896e-310,
        6.37576896e-310, 6.37576897e-310, 6.37576897e-310],
       [6.37576897e-310, 6.37576896e-310, 6.37576897e-310,
        6.37576902e-310, 6.37576909e-310, 6.37576898e-310],
       [6.37576898e-310, 6.37576902e-310, 6.37576974e-310,
        6.37576898e-310, 6.37576898e-310, 6.37576898e-310],
       [6.37576898e-310, 6.37576898e-310, 6.3757

In [50]:
arr.reshape((5,12))

array([[5.30306612e-310, 0.00000000e+000, 6.37576917e-310,
        6.37576906e-310, 6.37576907e-310, 6.37576906e-310,
        6.37576906e-310, 2.13930425e-321, 6.37576948e-310,
        6.37576948e-310, 6.37576906e-310, 6.37576902e-310],
       [6.37576906e-310, 6.37576905e-310, 6.37576896e-310,
        6.37576905e-310, 6.37576906e-310, 6.37576906e-310,
        6.37576971e-310, 6.37576904e-310, 6.37576906e-310,
        6.37576904e-310, 6.37576973e-310, 6.37576896e-310],
       [6.37576897e-310, 6.37576896e-310, 6.37576897e-310,
        6.37576896e-310, 6.37576897e-310, 6.37576897e-310,
        6.37576897e-310, 6.37576896e-310, 6.37576896e-310,
        6.37576896e-310, 6.37576897e-310, 6.37576897e-310],
       [6.37576897e-310, 6.37576896e-310, 6.37576897e-310,
        6.37576902e-310, 6.37576909e-310, 6.37576898e-310,
        6.37576898e-310, 6.37576902e-310, 6.37576974e-310,
        6.37576898e-310, 6.37576898e-310, 6.37576898e-310],
       [6.37576898e-310, 6.37576898e-310, 6.37576899

In [51]:
arr.reshape((5,10)) #doesn't work because the number of elements must be the same

ValueError: cannot reshape array of size 60 into shape (5,10)

In [38]:
arr.reshape((-1,15)) # -1 mean derive from number of column the number of the row to contain all the elements

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 2., 2., 2.],
       [2., 2., 2., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6., 7., 7., 7.],
       [7., 7., 7., 8., 8., 8., 8., 8., 8., 9., 9., 9., 9., 9., 9.]])

In [52]:
arr.reshape((3,2,10))

array([[[5.30306612e-310, 0.00000000e+000, 6.37576917e-310,
         6.37576906e-310, 6.37576907e-310, 6.37576906e-310,
         6.37576906e-310, 2.13930425e-321, 6.37576948e-310,
         6.37576948e-310],
        [6.37576906e-310, 6.37576902e-310, 6.37576906e-310,
         6.37576905e-310, 6.37576896e-310, 6.37576905e-310,
         6.37576906e-310, 6.37576906e-310, 6.37576971e-310,
         6.37576904e-310]],

       [[6.37576906e-310, 6.37576904e-310, 6.37576973e-310,
         6.37576896e-310, 6.37576897e-310, 6.37576896e-310,
         6.37576897e-310, 6.37576896e-310, 6.37576897e-310,
         6.37576897e-310],
        [6.37576897e-310, 6.37576896e-310, 6.37576896e-310,
         6.37576896e-310, 6.37576897e-310, 6.37576897e-310,
         6.37576897e-310, 6.37576896e-310, 6.37576897e-310,
         6.37576902e-310]],

       [[6.37576909e-310, 6.37576898e-310, 6.37576898e-310,
         6.37576902e-310, 6.37576974e-310, 6.37576898e-310,
         6.37576898e-310, 6.37576898e-310, 6.375

#### Change the data type of an array.

In [ ]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)

In [ ]:
y= x.astype(float)

In [ ]:
y

#### Joining and splitting of arrays
- Combining multiple arrays into one, and splitting one array into many
  - np.concatenate takes a tuple or list of arrays as its first argument

In [40]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [ ]:
x

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
y

In [54]:
np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.concatenate([x,y],axis=1) #doesn't work because x and y are mono-dimensional array

AxisError: axis 1 is out of bounds for array of dimension 1

In [41]:
xR=x.reshape(1,-1)
yR=y.reshape(1,-1)

In [42]:
xR

array([[1, 2, 3, 4, 5]])

In [43]:
xR.ndim

2

In [59]:
xR.shape

(1, 5)

In [44]:
np.concatenate([xR,yR])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
np.concatenate([xR,yR], axis=1) #now it works

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [62]:
np.concatenate([x,y,x,x,y,x,y,x,y,x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10])

In [47]:
arrSmall = np.array([[1,2,3],[4,5,6]])

In [48]:
arrSmall

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([arrSmall,arrSmall], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions


In [1]:
x = np.array([1,2,3])
y = np.array([[4,5,6],[7,8,9]])

NameError: name 'np' is not defined

In [ ]:
x

In [68]:
y

array([[4, 5, 6],
       [7, 8, 9]])

In [66]:
np.vstack([x,y]) #vertical concatenation

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.hstack([y,y]) #horizontal concatenation

array([[4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [50]:
x = np.hstack([x,x,x,x])
x

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

- The opposite of concatenation is splitting, which is implemented by the functions np.split


In [76]:
np.split(x,[3,6,7]) #the second parameter is the index where split array

[array([1, 2, 3]), array([1, 2, 3]), array([1]), array([2, 3, 1, 2, 3])]

In [51]:
y

array([ 6,  7,  8,  9, 10])

In [52]:
z,k = np.split(y,[2])

In [53]:
z

array([6, 7])

In [54]:
k

array([ 8,  9, 10])

## Computation on NumPy Arrays:



- Any arithmetic operations between equal-size arrays applies the operation elementwise
- Arithmetic operations with scalars are propagating the value to each element

In [77]:
arr1 = np.random.randint(10,size= (10,10))
arr2 = np.random.randint(10,size= (10,10))

In [78]:
arr1

array([[1, 5, 9, 8, 8, 1, 4, 7, 7, 3],
       [8, 3, 1, 7, 7, 5, 7, 7, 9, 9],
       [5, 2, 8, 1, 4, 3, 5, 0, 1, 7],
       [5, 3, 5, 5, 0, 7, 1, 3, 1, 2],
       [7, 5, 5, 1, 4, 4, 1, 0, 7, 2],
       [9, 6, 0, 2, 5, 6, 7, 6, 5, 8],
       [7, 6, 9, 1, 8, 2, 8, 2, 5, 6],
       [7, 5, 7, 2, 9, 7, 6, 0, 0, 8],
       [9, 5, 8, 8, 7, 4, 0, 1, 5, 0],
       [4, 1, 5, 6, 1, 0, 5, 1, 2, 7]])

In [79]:
arr1 * 125

array([[ 125,  625, 1125, 1000, 1000,  125,  500,  875,  875,  375],
       [1000,  375,  125,  875,  875,  625,  875,  875, 1125, 1125],
       [ 625,  250, 1000,  125,  500,  375,  625,    0,  125,  875],
       [ 625,  375,  625,  625,    0,  875,  125,  375,  125,  250],
       [ 875,  625,  625,  125,  500,  500,  125,    0,  875,  250],
       [1125,  750,    0,  250,  625,  750,  875,  750,  625, 1000],
       [ 875,  750, 1125,  125, 1000,  250, 1000,  250,  625,  750],
       [ 875,  625,  875,  250, 1125,  875,  750,    0,    0, 1000],
       [1125,  625, 1000, 1000,  875,  500,    0,  125,  625,    0],
       [ 500,  125,  625,  750,  125,    0,  625,  125,  250,  875]])

In [80]:
arr1 + arr2 #only if arrays have the same shape

array([[ 7, 12, 15, 11, 13,  7,  7, 13, 14,  9],
       [15, 10, 10, 14,  7,  6, 14,  9, 18, 16],
       [14,  3, 15,  5, 13,  7, 12,  6,  3, 12],
       [ 8,  9,  6, 11,  4, 16,  8,  4,  8,  9],
       [14,  5, 14,  4,  5, 12,  7,  0, 12,  2],
       [12, 12,  1,  2,  7,  9, 16,  6,  6, 17],
       [16, 12, 18,  4,  9,  8, 17,  3, 11, 12],
       [14,  5,  7,  9, 15,  8, 15,  3,  2, 16],
       [18,  9, 10, 12, 13,  7,  7,  5,  6,  3],
       [12,  3,  5,  8,  5,  8,  8,  1, 11, 10]])

In [81]:
arr1 * arr2 - arr1 / ( arr2 +1)

array([[ 5.85714286, 34.375     , 52.71428571, 22.        , 38.66666667,
         5.85714286, 11.        , 41.        , 48.125     , 17.57142857],
       [55.        , 20.625     ,  8.9       , 48.125     , -7.        ,
         2.5       , 48.125     , 11.66666667, 80.1       , 61.875     ],
       [44.5       ,  1.        , 55.        ,  3.8       , 35.6       ,
        11.4       , 34.375     ,  0.        ,  1.66666667, 33.83333333],
       [13.75      , 17.57142857,  2.5       , 29.28571429,  0.        ,
        62.3       ,  6.875     ,  1.5       ,  6.875     , 13.75      ],
       [48.125     , -5.        , 44.5       ,  2.75      ,  2.        ,
        31.55555556,  5.85714286,  0.        , 33.83333333, -2.        ],
       [24.75      , 35.14285714,  0.        , -2.        ,  8.33333333,
        16.5       , 62.3       , -6.        ,  2.5       , 71.2       ],
       [62.3       , 35.14285714, 80.1       ,  2.75      ,  4.        ,
        11.71428571, 71.2       ,  1.        

- Transposing Arrays and inner matrix product

In [82]:
arr1

array([[1, 5, 9, 8, 8, 1, 4, 7, 7, 3],
       [8, 3, 1, 7, 7, 5, 7, 7, 9, 9],
       [5, 2, 8, 1, 4, 3, 5, 0, 1, 7],
       [5, 3, 5, 5, 0, 7, 1, 3, 1, 2],
       [7, 5, 5, 1, 4, 4, 1, 0, 7, 2],
       [9, 6, 0, 2, 5, 6, 7, 6, 5, 8],
       [7, 6, 9, 1, 8, 2, 8, 2, 5, 6],
       [7, 5, 7, 2, 9, 7, 6, 0, 0, 8],
       [9, 5, 8, 8, 7, 4, 0, 1, 5, 0],
       [4, 1, 5, 6, 1, 0, 5, 1, 2, 7]])

In [83]:
arr1.T

array([[1, 8, 5, 5, 7, 9, 7, 7, 9, 4],
       [5, 3, 2, 3, 5, 6, 6, 5, 5, 1],
       [9, 1, 8, 5, 5, 0, 9, 7, 8, 5],
       [8, 7, 1, 5, 1, 2, 1, 2, 8, 6],
       [8, 7, 4, 0, 4, 5, 8, 9, 7, 1],
       [1, 5, 3, 7, 4, 6, 2, 7, 4, 0],
       [4, 7, 5, 1, 1, 7, 8, 6, 0, 5],
       [7, 7, 0, 3, 0, 6, 2, 0, 1, 1],
       [7, 9, 1, 1, 7, 5, 5, 0, 5, 2],
       [3, 9, 7, 2, 2, 8, 6, 8, 0, 7]])

In [84]:
np.dot(arr1,arr1.T) 

array([[359, 316, 178, 150, 180, 230, 291, 238, 272, 172],
       [316, 457, 211, 179, 219, 377, 325, 304, 272, 212],
       [178, 211, 194, 117, 140, 193, 245, 246, 172, 148],
       [150, 179, 117, 148, 120, 161, 148, 166, 176, 102],
       [180, 219, 140, 120, 186, 197, 220, 197, 215, 101],
       [230, 377, 193, 161, 197, 356, 294, 290, 217, 166],
       [291, 325, 245, 148, 220, 294, 364, 326, 264, 187],
       [238, 304, 246, 166, 197, 290, 326, 357, 251, 175],
       [272, 272, 172, 176, 215, 217, 264, 251, 325, 147],
       [172, 212, 148, 102, 101, 166, 187, 175, 147, 158]])

### Mathematical and Statistical Methods

- A set of mathematical functions which compute statistics about an entire array or about the data along an axis are accessible as array methods.



Algebric operations

```
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)
```

Trigonometric functions:

```
sin, cos, tan	compute sine, cosine and tangent of angles
arcsin, arccos, arctan	calculate inverse sine, cosine and tangent
hypot	calculate hypotenuse of given right triangle
sinh, cosh, tanh	compute hyperbolic sine, cosine and tangent
arcsinh, arccosh, arctanh	compute inverse hyperbolic sine, cosine and tangent
deg2rad	convert degree into radians
rad2deg	convert radians into degree
```

Statistical functions:

```
amin, amax	returns minimum or maximum of an array or along an axis
ptp	returns range of values (maximum-minimum) of an array or along an axis
percentile(a, p, axis)	calculate pth percentile of array or along specified axis
median	compute median of data along specified axis
mean	compute mean of data along specified axis
std	compute standard deviation of data along specified axis
var	compute variance of data along specified axis
average	compute average of data along specified axis
```

In [ ]:
arr1

In [ ]:
np.median(arr1)

In [ ]:
np.add(arr1,arr2) #subtract, multiply, divide

In [ ]:
arr1+arr2

In [ ]:
np.sqrt(arr2)

In [ ]:
np.max(arr1)

In [ ]:
arr1

In [ ]:
arr2

In [55]:
np.maximum(arr1, arr2)

NameError: name 'arr2' is not defined

In [57]:
a = np.arange(1,11)
b = np.arange(10,20)

In [ ]:
a.mean()

In [58]:
a.sum()

55

In [ ]:
a.std()

In [59]:
a.var()

8.25

In [60]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [61]:
b.cumprod()

array([          10,          110,         1320,        17160,
             240240,      3603600,     57657600,    980179200,
        17643225600, 335221286400])

- np.where returns elements depending on condition

In [63]:
a = np.arange(1,11)

In [64]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.where(a>5,0,10)

array([10, 10, 10, 10, 10,  0,  0,  0,  0,  0])

In [66]:
b = np.arange(10,20)

In [67]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
np.where(a%2==1,a,b)

array([ 1, 11,  3, 13,  5, 15,  7, 17,  9, 19])

## Boolean Arrays

- Boolean values are coerced to 1 (True) and 0 (False) in the above methods.
- Sum is often used as a means of counting True values in a boolean array.


In [3]:
boola = np.random.randint(2, size=100)
boola

In [5]:
boola.sum()

53

In [6]:
bools = np.array([True,True,False,False,True])

In [7]:
bools.sum() #sum only true value

3

In [8]:
bools.any() #test whether any array element along a given axis evaluates to True.

True

In [9]:
bools.all() #Test whether all array elements along a given axis evaluate to True.

False

In [10]:
bools[:2].all()

True

## Sorting
- Like Python’s built-in list type, NumPy arrays can be sorted in-place using the sort method

In [11]:
arrsort =np.random.randn(4,3)

In [12]:
arrsort

array([[-1.08951024, -0.53797983, -0.54997151],
       [-0.32239026, -1.23763867,  0.72343896],
       [-1.0603797 , -1.15106138,  1.14967534],
       [-1.25618524,  0.84402137, -0.60348473]])

In [13]:
arrsort.sort(0) #axis along which to sort

In [14]:
arrsort

array([[-1.25618524, -1.23763867, -0.60348473],
       [-1.08951024, -1.15106138, -0.54997151],
       [-1.0603797 , -0.53797983,  0.72343896],
       [-0.32239026,  0.84402137,  1.14967534]])

In [15]:
arrsort.sort(1)

In [16]:
arrsort

array([[-1.25618524, -1.23763867, -0.60348473],
       [-1.15106138, -1.08951024, -0.54997151],
       [-1.0603797 , -0.53797983,  0.72343896],
       [-0.32239026,  0.84402137,  1.14967534]])

### Unique and Other Set Logic

- NumPy has some basic set operations for one-dimensional ndarrays.

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
np.unique(names)