In [7]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn import preprocessing

In [9]:
# 1. Download the dataset from https://archive.ics.uci.edu/ml/datasets/mushroom and insert it into the dataframe `mushroom`.
mushroom = pd.read_csv("data/agaricus-lepiota.data", sep=',', header=None)
mushroom_columns = ["target","cap-shape","cap-surface","cap-color","bruises","odor","gill-attachment","gill-spacing","gill-size","gill-color","stalk-shape","stalk-root",
                    "stalk-surface-above-ring","stalk-surface-below-ring","stalk-color-above-ring","stalk-color-below-ring","veil-type","veil-color","ring-number",
                    "ring-type","spore-print-color","population","habitat"]
mushroom.columns = mushroom_columns
mushroom

target cap-shape cap-surface cap-color bruises odor gill-attachment  \
0         p         x           s         n       t    p               f   
1         e         x           s         y       t    a               f   
2         e         b           s         w       t    l               f   
3         p         x           y         w       t    p               f   
4         e         x           s         g       f    n               f   
...     ...       ...         ...       ...     ...  ...             ...   
8119      e         k           s         n       f    n               a   
8120      e         x           s         n       f    n               a   
8121      e         f           s         n       f    n               a   
8122      p         k           y         n       f    y               f   
8123      e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [11]:
# 2. Transform the attribute values into numbers.
enc = preprocessing.OrdinalEncoder() # ordinal because we don't have boolean value
enc.fit(mushroom)
mushroom_encoded = pd.DataFrame(enc.transform(mushroom), columns=mushroom_columns)
mushroom_encoded

target  cap-shape  cap-surface  cap-color  bruises  odor  \
0        1.0        5.0          2.0        4.0      1.0   6.0   
1        0.0        5.0          2.0        9.0      1.0   0.0   
2        0.0        0.0          2.0        8.0      1.0   3.0   
3        1.0        5.0          3.0        8.0      1.0   6.0   
4        0.0        5.0          2.0        3.0      0.0   5.0   
...      ...        ...          ...        ...      ...   ...   
8119     0.0        3.0          2.0        4.0      0.0   5.0   
8120     0.0        5.0          2.0        4.0      0.0   5.0   
8121     0.0        2.0          2.0        4.0      0.0   5.0   
8122     1.0        3.0          3.0        4.0      0.0   8.0   
8123     0.0        5.0          2.0        4.0      0.0   5.0   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                 1.0           0.0        1.0         4.0  ...   
1                 1.0           0.0        0.0         4.0  ...   
2                 1.0           0.0        0.0         5.0  ...   
3                 1.0           0.0        1.0         5.0  ...   
4                 1.0           1.0        0.0         4.0  ...   
...               ...           ...        ...         ...  ...   
8119              0.0           0.0        0.0        11.0  ...   
8120              0.0           0.0        0.0        11.0  ...   
8121              0.0           0.0        0.0         5.0  ...   
8122              1.0           0.0        1.0         0.0  ...   
8123              0.0           0.0        0.0        11.0  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                          2.0                     7.0   
1                          2.0                     7.0   
2                          2.0                     7.0   
3                          2.0                     7.0   
4                          2.0                     7.0   
...                        ...                     ...   
8119                       2.0                     5.0   
8120                       2.0                     5.0   
8121                       2.0                     5.0   
8122                       1.0                     7.0   
8123                       2.0                     5.0   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                        7.0        0.0         2.0          1.0        4.0   
1                        7.0        0.0         2.0          1.0        4.0   
2                        7.0        0.0         2.0          1.0        4.0   
3                        7.0        0.0         2.0          1.0        4.0   
4                        7.0        0.0         2.0          1.0        0.0   
...                      ...        ...         ...          ...        ...   
8119                     5.0        0.0         1.0          1.0        4.0   
8120                     5.0        0.0         0.0          1.0        4.0   
8121                     5.0        0.0         1.0          1.0        4.0   
8122                     7.0        0.0         2.0          1.0        0.0   
8123                     5.0        0.0         1.0          1.0        4.0   

      spore-print-color  population  habitat  
0                   2.0         3.0      5.0  
1                   3.0         2.0      1.0  
2                   3.0         2.0      3.0  
3                   2.0         3.0      5.0  
4                   3.0         0.0      1.0  
...                 ...         ...      ...  
8119                0.0         1.0      2.0  
8120                0.0         4.0      2.0  
8121                0.0         1.0      2.0  
8122                7.0         4.0      2.0  
8123                4.0         1.0      2.0  

[8124 rows x 23 columns]

In [12]:
# 3. Calculate the accuracy (5-fold cross-validation) of the obtained dataset in predicting whether a mushroom is poisonous using 3 classifiers.
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, train_test_split

In [16]:
y = mushroom_encoded['target']
X = mushroom_encoded.loc[:,'cap-shape':'habitat']

In [17]:
lr = LogisticRegression()
scores = cross_val_score(lr,X,y, cv = 5)
print(scores)
scores.mean()

/usr/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimiz

[0.63015385 0.98338462 0.87569231 0.99815385 0.71366995]


/usr/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8402109132247064

In [18]:
svm = SVC(C=0.6)
scores = cross_val_score(svm,X,y, cv = 5)
print(scores)
scores.mean()

[0.80738462 0.99261538 0.88615385 1.         0.5       ]


0.8372307692307693

In [19]:
knn = KNeighborsClassifier(n_neighbors=4)
scores = cross_val_score(knn,X,y, cv = 5)
print(scores)
scores.mean()

[0.84246154 0.99753846 0.92430769 1.         0.65147783]


0.8831571049640015

In [51]:
# 4. Use only the attributes of the dataset that pertain to color (call the new dataset `mushroom_color`) and check if the accuracy changes.
mushroom_color = pd.DataFrame()

for column_name in mushroom.columns:
    if column_name.__contains__("color"):
        mushroom_color[column_name] = mushroom_encoded[column_name]

mushroom_color

cap-color  gill-color  stalk-color-above-ring  stalk-color-below-ring  \
0           4.0         4.0                     7.0                     7.0   
1           9.0         4.0                     7.0                     7.0   
2           8.0         5.0                     7.0                     7.0   
3           8.0         5.0                     7.0                     7.0   
4           3.0         4.0                     7.0                     7.0   
...         ...         ...                     ...                     ...   
8119        4.0        11.0                     5.0                     5.0   
8120        4.0        11.0                     5.0                     5.0   
8121        4.0         5.0                     5.0                     5.0   
8122        4.0         0.0                     7.0                     7.0   
8123        4.0        11.0                     5.0                     5.0   

      veil-color  spore-print-color  
0            2.0                2.0  
1            2.0                3.0  
2            2.0                3.0  
3            2.0                2.0  
4            2.0                3.0  
...          ...                ...  
8119         1.0                0.0  
8120         0.0                0.0  
8121         1.0                0.0  
8122         2.0                7.0  
8123         1.0                4.0  

[8124 rows x 6 columns]

In [23]:
lr = LogisticRegression()
scores = cross_val_score(lr,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.59507692 0.63384615 0.71569231 0.87507692 0.85652709]


0.7352438802576734

In [24]:
svm = SVC(C=0.6)
scores = cross_val_score(svm,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.70892308 0.95015385 0.81476923 1.         0.5794335 ]


0.8106559302766201

In [25]:
knn = KNeighborsClassifier(n_neighbors=4)
scores = cross_val_score(knn,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.73353846 0.94276923 0.92861538 1.         0.61637931]


0.8442604774535809

In [33]:
# 5.Create a new version of `mushroom_color` where, for each value of each feature, a boolean vector is created that assumes a value of 1 only for instances with that specific value in the original dataset. Verify if the accuracy changes.
enc = preprocessing.OneHotEncoder() 

mushroom_color = pd.DataFrame()

for column_name in mushroom.columns:
    if column_name.__contains__("color"):
        mushroom_color[column_name] = mushroom_encoded[column_name]
        
mushroom_color = enc.fit_transform(mushroom_color)
mushroom_color


<8124x53 sparse matrix of type '<class 'numpy.float64'>'
	with 48744 stored elements in Compressed Sparse Row format>

In [34]:
lr = LogisticRegression()
scores = cross_val_score(lr,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.73353846 0.99015385 0.97907692 1.         0.52894089]


0.8463420234937477

In [35]:
svm = SVC(C=0.6)
scores = cross_val_score(svm,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.73353846 0.95815385 0.92738462 1.         0.52894089]


0.8296035619552861

In [36]:
knn = KNeighborsClassifier(n_neighbors=4)
scores = cross_val_score(knn,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.73353846 0.92492308 0.90892308 0.99569231 0.67672414]


0.8479602122015916

In [43]:
# 6. Add an attribute from the original dataset to `mushroom_color` from point 4 in order to increase the accuracy.
mushroom_color = pd.DataFrame()

for column_name in mushroom.columns:
    if column_name.__contains__("color"):
        mushroom_color[column_name] = mushroom_encoded[column_name]

mushroom_color["bruises"] = mushroom_encoded["bruises"]
mushroom_color


cap-color  gill-color  stalk-color-above-ring  stalk-color-below-ring  \
0           4.0         4.0                     7.0                     7.0   
1           9.0         4.0                     7.0                     7.0   
2           8.0         5.0                     7.0                     7.0   
3           8.0         5.0                     7.0                     7.0   
4           3.0         4.0                     7.0                     7.0   
...         ...         ...                     ...                     ...   
8119        4.0        11.0                     5.0                     5.0   
8120        4.0        11.0                     5.0                     5.0   
8121        4.0         5.0                     5.0                     5.0   
8122        4.0         0.0                     7.0                     7.0   
8123        4.0        11.0                     5.0                     5.0   

      veil-color  spore-print-color  bruises  
0            2.0                2.0      1.0  
1            2.0                3.0      1.0  
2            2.0                3.0      1.0  
3            2.0                2.0      1.0  
4            2.0                3.0      0.0  
...          ...                ...      ...  
8119         1.0                0.0      0.0  
8120         0.0                0.0      0.0  
8121         1.0                0.0      0.0  
8122         2.0                7.0      0.0  
8123         1.0                4.0      0.0  

[8124 rows x 7 columns]

In [44]:
lr = LogisticRegression()
scores = cross_val_score(lr,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.67876923 0.62030769 0.72861538 0.96369231 0.77093596]


0.7524641151951498

In [45]:
svm = SVC(C=0.6)
scores = cross_val_score(svm,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.70892308 0.95261538 0.80061538 1.         0.55849754]


0.8041302766199317

In [46]:
knn = KNeighborsClassifier(n_neighbors=4)
scores = cross_val_score(knn,mushroom_color,y, cv = 5)
print(scores)
scores.mean()

[0.73353846 0.98646154 0.92123077 1.         0.62931034]


0.8541082228116711

In [54]:
# 7. Use a regression algorithm to calculate the edibility value. Use a 30% train/test split. Round to the nearest integer. Does the result change?
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [52]:
y = mushroom_encoded['target']

X_train, X_test, y_train, y_test = train_test_split(mushroom_color, y, test_size=0.3)

In [56]:
lr = LinearRegression()
lr.fit(X_train,y_train)

accuracy_score(y_test, np.round(lr.predict(X_test))) # round the prediction

0.7928630024610336

In [57]:
# 8. Evaluate some possible configurations of a model of your choice.
from sklearn.model_selection import GridSearchCV

In [59]:
y = mushroom_encoded['target']
X = mushroom_encoded.loc[:,'cap-shape':'habitat']

In [60]:
knn = KNeighborsClassifier()

In [61]:

parameters = {'n_neighbors':[3, 5, 9], 
              'weights':['uniform', 'distance'],
              'leaf_size':[15, 30, 45]
              }
clf = GridSearchCV(knn, parameters, cv=5, n_jobs=-1)
clf.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'leaf_size': [15, 30, 45], 'n_neighbors': [3, 5, 9],
                         'weights': ['uniform', 'distance']})

In [64]:
clf.best_estimator_

KNeighborsClassifier(leaf_size=15, n_neighbors=3, weights='distance')

In [62]:
clf.best_params_

{'leaf_size': 15, 'n_neighbors': 3, 'weights': 'distance'}

In [63]:
clf.best_score_

0.8926348616900341