In [14]:
import numpy as np
import time

 Write a function that takes a 1d numpy array and computes its reverse vector (last element becomes the first).


In [7]:
arr2 = np.array([0.3,2.,5.9,7.3])
arr2[::-1]

array([7.3, 5.9, 2. , 0.3])

Given the following square array, compute the product of the elements on its
diagonal. [[1 3 8] [-1 3 0] [-3 9 2]]


In [6]:
array =  [[1,3,8],[-1,3,0],[-3,9,2]]
np.prod(np.diag(array))

6

Create a random vector of size (3, 6) and find its mean value.


In [2]:
array = np.empty((3,6))
np.mean(array)

6.2920749436773e-310

• Given two arrays a and b, compute how many time an item of a is higher than the corresponding element of b.

a: [[1 5 6 8] [2 -3 13 23] [0 -10 -9 7]]

b: [[-3 0 8 1] [-20 -9 -1 32] [7 7 7 7]]


In [4]:
a = [[1,5,6,8],[2,-3,13,23],[0,-10,-9,7]]
b = [[-3,0,8,1],[-20,-9,-1,32],[7,7,7,7]]

array_a = np.array(a)
array_b = np.array(b)

np.count_nonzero(array_a > array_b)

6

Create and normalize the following matrix (use min-max normalization):
[[0.35 -0.27 0.56] [0.15 0.65 0.42] [0.73 -0.78 -0.08]]

In [5]:
array = [[0.35, -0.27, 0.56],[0.15, 0.65, 0.42],[0.73, -0.78, -0.08]]
array = np.array(array)

array = (array - np.min(array)) / (np.max(array) - np.min(array))
array

array([[0.74834437, 0.33774834, 0.88741722],
       [0.61589404, 0.94701987, 0.79470199],
       [1.        , 0.        , 0.46357616]])

Let’s run a little benchmark! Given a matrix A ∈ RNxM and a vector b ∈ RM ,
compute the euclidean distance between b and each row Ai.

By filling in the blanks in eucl distance.py, implement this simple function twice:
*   with vanilla Python operators,
*   with optimized Numpy operations.

Which one runs faster? Read the provided code carefully and watch out for mistakes.

In [15]:
a = [[1,5,6,8],[2,-3,13,23],[0,-10,-9,7]]
b = [[-3,0,8,1]]

array_a = np.array(a)
array_b = np.array(b)

start_time = time.time()
dist = np.linalg.norm(array_a - array_b, axis=1)
print(dist)
print("--- %s seconds ---" % (time.time() - start_time))

[ 9.69535971 23.3023604  20.83266666]
--- 0.0022382736206054688 seconds ---


In [17]:
a = [[1,5,6,8],[2,-3,13,23],[0,-10,-9,7]]
b = [[-3,0,8,1]]

start_time = time.time()
dist = []
for row in a:
  sum = 0
  for i in range(len(row)):
    sum += (row[i] - b[0][i]) ** 2
  dist.append(sum ** 0.5)
print(dist)
print("--- %s seconds ---" % (time.time() - start_time))

[9.695359714832659, 23.302360395462088, 20.83266665599966]
--- 0.0021657943725585938 seconds ---
